#_____  ______ _____   ____  _____ _______ _____
#|  __ \|  ____|  __ \ / __ \|  __ \__   __/ ____|
#| |__) | |__  | |__) | |  | | |__) | | | | (___
#|  _  /|  __| |  ___/| |  | |  _  /  | |  \___ \
#| | \ \| |____| |    | |__| | | \ \  | |  ____) |
#|_|  \_\______|_|     \____/|_|  \_\ |_| |_____/

# Thank you for downloading the reports plugin.

# Here you can enter your data to the MySQL database.
MySQL:
  Port: 3306
  Host: 'localhost'
  Username: 'root'
  Password: '123'
  Database: 'test'